baseURL = "https://brtkcs.com/"
languageCode = "hu"
title = "@brtkcs | ~/werkstatt"
theme = "brtkcs"

[pagination]
  pagerSize = 10

enableRobotsTXT = true
enableGitInfo = true

[params]
  description = "Filozófia, versek, gondolatok és podcast"
  author = "brtkcs"

  [params.colors]
    beige = "#D7D4CD"
    olive = "#848B23"
    rust = "#A8361B"
    darkBrown = "#433C22"
    purple = "#31185A"
    nearBlack = "#191202"
    black = "#000000"

  [params.social]
    github = "https://github.com/brtkcs"
    bluesky = "https://bsky.app/profile/brtkcs.com"
    instagram = "https://instagram.com/brtkcs00"
    mastodon = "https://mastodon.social/@brtkcs"

[menu]
  [[menu.main]]
    name = "@Források"
    url = "/source/"
    weight = 1
  [[menu.main]]
    name = "Podcast"
    url = "https://tinnitus.pods-blitz.org"
    weight = 2
  [[menu.main]]
    name = "Filozófia"
    url = "/filozofia/"
    weight = 3
  [[menu.main]]
    name = "Versek"
    url = "/versek/"
    weight = 4
  [[menu.main]]
    name = "Art or.."
    url = "https://jokerpakli.brtkcs.com/"
    weight = 5
  [[menu.main]]
    name = "Links"
    url = "https://links.brtkcs.com"
    weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[permalinks]
  source = "/source/:year/:month/:slug/"
  podcast = "/podcast/:slug/"
  filozofia = "/filozofia/:slug/"
  versek = "/versek/:slug/"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.bluesky]
    disable = false
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
